config/routes.rb
Rails.application.routes.draw do
  resources :weight_histroys
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/', to: 'top#index'

  get 'users', to: 'users#index', as: "users"
  get 'users/:id', to: 'users#show', as: "user"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  has_many :weight_histroys
end

app/models/weight_histroy.rb
class WeightHistroy < ApplicationRecord
  belongs_to :user

  before_validation :set_memo

  validates :user_id, presence: { message: "ユーザを入力してください" }
  validates :memo, length: { maximum: 255, too_long: "メモは最大%{count}文字以内で入力してください" }
  validate :weight_validate

  def weight_validate
    if weight < 1
      errors.add(:weight, "体重が正しくありません")
    end
  end

  def set_memo
    if memo.nil?
      self.memo = "なし"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    params["id"]
    @user = User.find(params["id"])
  end
end

app/controllers/weight_histroys_controller.rb
class WeightHistroysController < ApplicationController
  before_action :set_weight_histroy, only: %i[ show edit update destroy ]

  def index
    @weight_histroys = WeightHistroy.all
  end

  def show
  end

  def new
    @weight_histroy = WeightHistroy.new
  end

  def edit
  end

  def create
    @weight_histroy = WeightHistroy.new(weight_histroy_params)

    respond_to do |format|
      if @weight_histroy.save
        format.html { redirect_to weight_histroy_url(@weight_histroy), notice: "Weight histroy was successfully created." }
        format.json { render :show, status: :created, location: @weight_histroy }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @weight_histroy.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @weight_histroy.update(weight_histroy_params)
        format.html { redirect_to weight_histroy_url(@weight_histroy), notice: "Weight histroy was successfully updated." }
        format.json { render :show, status: :ok, location: @weight_histroy }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @weight_histroy.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @weight_histroy.destroy

    respond_to do |format|
      format.html { redirect_to weight_histroys_url, notice: "Weight histroy was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_weight_histroy
      @weight_histroy = WeightHistroy.find(params[:id])
    end
    
    def weight_histroy_params
      params.require(:weight_histroy).permit(:user_id, :weight, :memo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weight_histroys_helper.rb
module WeightHistroysHelper
  def weight_comment(weight)
    if weight < 20
      "#{weight} (痩せ型)"
    else
      "#{weight} (普通または肥満体型)"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gold</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/index.html.erb
<h1>Hello</h1>

<%= link_to 'weight history', weight_histroys_path %>

app/views/users/index.html.erb
<h1>ユーザー詳細</h1>

<% @users.each do |user| %>
  <%= link_to user.name, user_path(id: user.id) %><br>
<% end %>

app/views/users/show.html.erb
<h1>ユーザー詳細</h1>

<%= @user.name %><br>
<%= @user.age %>才<br>

<%= link_to "戻る", users_path %>

app/views/weight_histroys/_form.html.erb
<%= form_with(model: weight_histroy) do |form| %>
  <% if weight_histroy.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(weight_histroy.errors.count, "error") %> prohibited this weight_histroy from being saved:</h2>

      <ul>
        <% weight_histroy.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :weight, style: "display: block" %>
    <%= form.number_field :weight %>
  </div>

  <div>
    <%= form.label :memo, style: "display: block" %>
    <%= form.text_field :memo %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/weight_histroys/_weight_histroy.html.erb
<div id="<%= dom_id weight_histroy %>">
  <p>
    <strong>User:</strong>
    <%= weight_histroy.user.name %>
  </p>

  <p>
    <strong>Weight:</strong>
    <%= weight_histroy.weight %>
  </p>

  <p>
    <strong>Memo:</strong>
    <%= weight_histroy.memo %>
  </p>

</div>

app/views/weight_histroys/edit.html.erb
<h1>Editing weight histroy</h1>

<%= render "form", weight_histroy: @weight_histroy %>

<br>

<div>
  <%= link_to "Show this weight histroy", @weight_histroy %> |
  <%= link_to "Back to weight histroys", weight_histroys_path %>
</div>

app/views/weight_histroys/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Weight histroys</h1>

<div id="weight_histroys">
  <% @weight_histroys.each do |weight_histroy| %>
    <%= render weight_histroy %>
    <p>
      <%= link_to "Show this weight histroy", weight_histroy %>
    </p>
  <% end %>
</div>

<%= link_to "New weight histroy", new_weight_histroy_path %>

app/views/weight_histroys/new.html.erb
<h1>New weight histroy</h1>

<%= render "form", weight_histroy: @weight_histroy %>

<br>

<div>
  <%= link_to "Back to weight histroys", weight_histroys_path %>
</div>

app/views/weight_histroys/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @weight_histroy %>

<div>
  <%= link_to "Edit this weight histroy", edit_weight_histroy_path(@weight_histroy) %> |
  <%= link_to "Back to weight histroys", weight_histroys_path %>

  <%= button_to "Destroy this weight histroy", @weight_histroy, method: :delete %>
</div>